---
- hosts: myswitches
  connection: local

  vars:
    backup_root: /etc/ansible/backups
  
  tasks:
    - name: GET CREDENTIALS
      include_vars: creds.yml

    - name: DEFINE CONNECTION
      set_fact:
         connection:
            authorize: yes
            host: "{{ inventory_hostname }}"
            username: "{{ creds['username'] }}"
            password: "{{ creds['password'] }}"
            auth_pass: "{{ creds['auth_pass'] }}"

    - name: run show running-config on remote devices
      ios_command:
        commands: show running
        provider: "{{ connection }}"
      register: config

    - name: ensure backup folder is created
      file:
        path: "{{ backup_root }}"
        state: directory
      run_once: yes

    - name: ensure device rolder is created
      file:
        path: "{{ backup_root }}/{{ inventory_hostname }}"
        state: directory

    - name: get timestamp
      command: date +%Y%m%d
      register: timestamp

    - copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ backup_root }}/{{ inventory_hostname }}/running-config_{{ timestamp.stdout }}"

  roles:
    - { role: slack,  message: '{{ inventory_hostname }} configuration backup completed'}


